name: CommandPack
main: CommandPack\Coammands
api: [3.0.0-ALPHA12]
version: 1.0.0
author: benzo

commands:
 feed:
  description: "Use feed command"
  permission: use.feed

heal:
 description: "Use heal command"
 permission: use.heal

 cure:
 description: "Use cure command"
 permission: use.cure
 
 fly:
 description: "Use fly command"
 permission: use.fly
 
 clearinv:
 description: "Use clearinv command"
 permission: use.clearinv
